### ISSUE TITLE
UI design standardization

### ISSUE THREAD

**Issue by juslar** [espresso-org/drive-components#15]
### Description

Standardize our UI between every section. Reach consensus on naming, buttons, headers, colors, etc and applying it to the application so we can have a uniform look going forward.

**Comment by macor161** [comment]
Some of the modifications that need to be made:

- Remove cancel buttons
- Reset every panel/selection when exiting
- Button list in "Details" panel (enabled/disabled) (colors/themes)
- Selectable boxes height (side panel, main screen)
- Checkboxes icon + checkboxes bug on mac
- Hide "Details" panel when empty
- Screen titles
- Input boxes (length/labels)
- Choose naming for address/entity/member
- Large blue buttons for main operations
- Align elements in permissions side panel

**Comment by juslar** [comment]
I'll add styling and chosing where to put the public file checkbox. It's implemented but doesn't look good right now. Wanted your opinion first.

**Comment by macor161** [comment]
Just saw your comment! What do you think of above the add/remove buttons or below the permission list, with a separator between them?

**Comment by juslar** [comment]
Implemented on master branch.
